"""add push_dead_letters table

Revision ID: 5b6702eb4d5b
Revises: 2d92c68e7ea2
Create Date: 2026-06-25 15:18:35.616448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6702eb4d5b'
down_revision: Union[str, Sequence[str], None] = '2d92c68e7ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_dead_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_dead_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_dead_letters_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_dead_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_dead_letters_subscription_id'))

    op.drop_table('push_dead_letters')
    # ### end Alembic commands ###
