"""init schema

Revision ID: b109a52b6784
Revises: 
Create Date: 2026-06-25 00:46:40.646892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b109a52b6784'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('spider_config', sa.JSON(), nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_crawl_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_sources_source_id'), ['source_id'], unique=True)

    op.create_table('policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.Column('summary_type', sa.String(length=32), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('summary_data', sa.JSON(), nullable=True),
    sa.Column('summary_model', sa.String(length=64), nullable=True),
    sa.Column('summarized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['policy_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_url'), ['url'], unique=True)

    op.create_table('push_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_logs_policy_id'), ['policy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_logs_policy_id'))

    op.drop_table('push_logs')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_url'))
        batch_op.drop_index(batch_op.f('ix_policies_source_id'))

    op.drop_table('policies')
    with op.batch_alter_table('policy_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_sources_source_id'))

    op.drop_table('policy_sources')
    # ### end Alembic commands ###
